<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Business extends Model
{
    //
    protected $guarded = [];

    public function business_owner()
    {
        return $this->hasOne(User::class,'id','created_by');
    }

    public function category()
    {
        return $this->hasOne(BusinessCategory::class, 'id', 'business_category_id');
    }

    public function recommendations()
    {
        return $this->hasMany(BusinessRecommendations::class, 'business_id');
    }

    public function reviews()
    {
        return $this->hasMany(UserBusinessRecommendation::class, 'business_id');
    }

    public function business_images()
    {
        return $this->hasMany(BusinessImages::class, 'business_id');
    }

    public function front_page_business_images()
    {
        return $this->hasMany(BusinessImages::class, 'business_id')->take(2)->latest();
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        // Deletes all the relations associated with user whenever a User is deleted via $user->delete()
        static::deleting(function ($business) { // Delete Recommendation
            $business->recommendations()->each(function ($recommendation) {
                $recommendation->delete(); // <-- direct deletion
            });
            $business->reviews()->each(function ($review) {
                $review->delete();
            });
            $business->business_images()->each(function ($image) {
                \File::delete(public_path('storage/business_pages/business-' . $image->business_id . '/' . basename($image->image_url)));
                $image->delete();
            });
        });
    }

}
