<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Business extends Model
{
    //
    protected $guarded = [];

    public function business_owner()
    {
        return $this->hasOne(User::class,'id','created_by');
    }

    public function category()
    {
        return $this->hasOne(BusinessCategory::class,'id','business_category_id');
    }

    public function recommendations()
    {
        return $this->hasMany(BusinessRecommendations::class,'business_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // Deletes all the relations associated with user whenever a User is deleted via $user->delete()

        static::deleting(function ($recommendations) { // Delete Recommendation
            $recommendations->recommendations()->each(function ($recommendation) {
                $recommendation->delete(); // <-- direct deletion
            });
        });
    }

}
