<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    //
    protected $guarded = [];

    public function interests()
    {
        return $this->hasMany(EventInterest::class, 'event_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo(EventCategory::class, 'event_category_id');
    }
    public function creator()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($event) {
            \File::delete(public_path('events/' . auth()->user()->id . basename($event->event_cover_photo)));
            $event->interests()->each(function ($ev_int) {
                $ev_int->delete();
            });
        });
    }

}
