<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = [];

    protected $with = ['likes', 'dislikes', 'comments'];

    public function scopeSectionPosts($query, $section = 'news-feed')
    {
        return $query->latest()->with('user')->whereSection($section)->paginate(10);
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(function ($post) {
            $post->likes()->each(function ($liked_post) {
                $liked_post->delete(); // <-- direct deletion
            });
            $post->dislikes()->each(function ($disliked_post) {
                $disliked_post->delete(); // <-- direct deletion
            });
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function likes()
    {
        return $this->hasMany(PostLike::class, 'post_id', 'id')->whereLikeDislike(1);
    }

    public function dislikes()
    {
        return $this->hasMany(PostLike::class, 'post_id', 'id')->where('like_dislike', '!=', 1);
    }

    public function comments()
    {
        return $this->hasMany(PostComment::class, 'post_id', 'id')->latest();
    }
}
