<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $with = ['user_extra'];


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     *
     */

    protected $guarded = [];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function is_admin()
    {
        if ($this->admin) {
            return true;
        }
        return false;
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        // Creates User Extra Settings And Attact it with the created User
        static::created(function ($user) {
            $user_extra = new UserExtra();
            $user_extra->user_id = $user->id;
            $user_extra->emergency_contact = '';
            $user_extra->bio = '';
            $user_extra->hide_phone = 0;
            $user_extra->hide_address = 0;
            $user_extra->save();

            $user->notify(new \App\Notifications\UserRegisteredNotification($user));
        });

        // Deletes all the relations associated with user whenever a User is deleted via $user->delete()

        static::deleting(function ($family_members) { // delete Family Members
            $family_members->family_members()->each(function ($member) {
                $member->delete(); // <-- direct deletion
            });

            $family_members->posts()->each(function ($post) { // Delete Posts
                $post->delete(); // <-- direct deletion
            });

            $family_members->identities()->each(function ($identity) {
                $identity->delete();
            });

            $family_members->user_extra()->delete(); // Deletes User Extra Settings
        });
    }
    public function user_extra()
    {
        return $this->hasOne(UserExtra::class, 'user_id', 'id');
    }

    // User can have many family Members
    public function family_members()
    {
        return $this->hasMany(FamilyMember::class, 'user_id');
    }

    // User can have many posts
    public function posts()
    {
        return $this->hasMany(Post::class, 'user_id');
    }

    public function identities()
    {
        return $this->hasMany('App\SocialIdentity');
    }

    public function sale_items()
    {
        return $this->hasMany(SaleItems::class,'user_id','id');
    }
}
